name: Wiki Sync

on:
  workflow_dispatch:
  
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    name: Wiki sync
    steps:
      - uses: OrlovM/Wiki-Action@v1
        with:
          path: 'docs/wiki'
          token: ${{ secrets.GH_TOKEN }}
